services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]      # контейнер не выходит мгновенно
    networks: ["scalable-db-net"]
    depends_on: ["mysql", "postgres"]

  mysql:
    image: mysql:8.0
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shard0
    ports:
      - "33060:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks: ["scalable-db-net"]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shard0
    ports:
      - "54320:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks: ["scalable-db-net"]

networks:
  scalable-db-net:

volumes:
  mysql-data:
  pg-data: