# CI: unit + feature tests for Scalable DB
name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  pest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:   [ '8.2', '8.4' ]
        db:    [ sqlite, mysql ]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: shard0
        ports: [ '3306:3306' ]
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -p$$MYSQL_ROOT_PASSWORD"
          --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo_mysql, pdo_sqlite, intl, zip
          coverage: none

      - name: Composer install
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Configure DB connection (MySQL / SQLite)
        run: |
          if [ "${{ matrix.db }}" = "mysql" ]; then
            echo "DB_CONNECTION=mysql"       >> $GITHUB_ENV
            echo "DB_HOST=127.0.0.1"         >> $GITHUB_ENV
            echo "DB_PORT=3306"              >> $GITHUB_ENV
            echo "DB_DATABASE=shard0"        >> $GITHUB_ENV
            echo "DB_USERNAME=root"          >> $GITHUB_ENV
            echo "DB_PASSWORD=root"          >> $GITHUB_ENV
          else
            echo "DB_CONNECTION=sqlite"      >> $GITHUB_ENV
            echo "DB_DATABASE=:memory:"      >> $GITHUB_ENV
          fi

      - name: Run tests (Pest)
        run: composer test